USE MimadosDB
GO

CREATE TABLE [CustomerEmail]
(
    Id INT IDENTITY PRIMARY KEY,
    CustomerId INT FOREIGN KEY REFERENCES [Customer](Id),
    Email VARCHAR(100) UNIQUE NOT NULL,
    Active BIT DEFAULT 1 NOT NULL
)
