USE MimadosDB
GO

CREATE TABLE [SupplierEmail]
(
    Id INT IDENTITY PRIMARY KEY,
    SupplierId INT FOREIGN KEY REFERENCES [Supplier](Id),
    Email VARCHAR(9) UNIQUE NOT NULL,
    Active BIT DEFAULT 1 NOT NULL
)
